### ISSUE TITLE
Using only shortcuts for next or previous methods 

### ISSUE THREAD

**Issue by FahadAijaz** [mishkinf/vscode-goto-next-previous-member#7]
Please can someone help me regarding the usage of navigating only across functions.

Assume I have defined this in my settings.json:
`// Enable a select few symbols
  "gotoNextPreviousMember.symbolKinds": [
    "function"
  ]`

From here on I'd like to use ctrl+shift+up to go to the previous function in the file.

**Comment by TheTastefulToastie** [comment]
What exactly isn't working? Does it jump to every symbol? Does it not jump at all?

If your settings.json is configured _exactly_ as you've written above, it won't work since the whole thing is a single-line comment.

Also what language are you using? e.g. Java doesn't have functions, it has only methods since all code must be contained within classes, so you will need to specify "method" instead of "function".

I've just tried it for JavaScript and it worked for me, here's what I did:

## keybindings.json
```json5
// Place your key bindings in this file to override the defaults
[

  // Unbind the default shortcuts
  {
    "key": "ctrl+down",
    "command": "-gotoNextPreviousMember.nextMember"
  },
  {
    "key": "ctrl+up",
    "command": "-gotoNextPreviousMember.previousMember"
  },

  // Bind my shortcuts instead
  {
    "key": "ctrl+shift+down",
    "command": "gotoNextPreviousMember.nextMember"
  },
  {
    "key": "ctrl+shift+up",
    "command": "gotoNextPreviousMember.previousMember"
  }

]
```

## settings.json
```json5
{
  // Enable a select few symbols
  "gotoNextPreviousMember.symbolKinds": [ "function" ]
}
```

**Comment by FahadAijaz** [comment]
Sorry, for being unclear. This was not a complaint of a feature not working. But I was unsure of what to exactly write in my settings.json. But now I understand. Thanks.

**Comment by TheTastefulToastie** [comment]
cool no problem :+1:
